version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: lyrics-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./docker-compose/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker-compose/elasticsearch/data:/usr/share/elasticsearch/data/
    environment:
      discovery.type: single-node
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      cluster.name: elasticsearch
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 5s
      timeout: 10s
      retries: 120
    restart: unless-stopped

  logstash:
    image: logstash:8.12.2
    container_name: lyrics-logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./docker-compose/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./docker-compose/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker-compose/logstash/data:/usr/share/logstash/data
      - ./logs:/var/logs
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  kibana:
    image: kibana:8.12.2
    container_name: lyrics-kibana
    ports:
      - "5601:5601"
    volumes:
      - ./docker-compose/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./docker-compose/kibana/data:/usr/share/kibana/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
