version: '3.8'

services:

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: lyrics-kafka1
    container_name: lyrics-kafka1
    ports:
      - "39092:39092"
    environment:
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: IC8PnUQMSnO6OJdfSV19Kw
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: BROKER://lyrics-kafka1:19092,EXTERNAL://lyrics-kafka1:39092,CONTROLLER://lyrics-kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://lyrics-kafka1:19092,EXTERNAL://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@lyrics-kafka1:9093,2@lyrics-kafka2:9093,3@lyrics-kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-compose/kafka/data/kafka1:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    hostname: lyrics-kafka2
    container_name: lyrics-kafka2
    ports:
      - "39093:39093"
    environment:
      CLUSTER_ID: IC8PnUQMSnO6OJdfSV19Kw
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: BROKER://lyrics-kafka2:19093,EXTERNAL://lyrics-kafka2:39093,CONTROLLER://lyrics-kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://lyrics-kafka2:19093,EXTERNAL://localhost:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@lyrics-kafka1:9093,2@lyrics-kafka2:9093,3@lyrics-kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-compose/kafka/data/kafka2:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    hostname: lyrics-kafka3
    container_name: lyrics-kafka3
    ports:
      - "39094:39094"
    environment:
      CLUSTER_ID: IC8PnUQMSnO6OJdfSV19Kw
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: BROKER://lyrics-kafka3:19094,EXTERNAL://lyrics-kafka3:39094,CONTROLLER://lyrics-kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://lyrics-kafka3:19094,EXTERNAL://localhost:39094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@lyrics-kafka1:9093,2@lyrics-kafka2:9093,3@lyrics-kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-compose/kafka/data/kafka3:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: lyrics-kafka-kafdrop
    ports:
      - "9099:9000"
    environment:
      KAFKA_BROKERCONNECT: "lyrics-kafka1:19092,lyrics-kafka2:19093,lyrics-kafka3:19094"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
