version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: lyrics-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker-compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.3.1
    container_name: lyrics-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./docker-compose/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker-compose/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro

  redis:
    image: redis:7.2.4
    container_name: lyrics-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - .env

  mongo_db:
    image: mongo:7.0.6
    container_name: lyrics-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$DB_USER_PASS
      - MONGO_INITDB_DATABASE=usersdb
    ports:
      - "27017:27017"
    volumes:
      - ./docker-compose/db:/data/db

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:3.1.1
    container_name: lyrics-zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=elasticsearch
      - DISCOVERY_EUREKA_ENABLED=true
      - EUREKA_APP_NAME=lyrics-zipkin
      - EUREKA_HOSTNAME=lyrics-zipkin
      # https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#service-registration
      - EUREKA_SERVICE_URL=http://$EUREKA_USER_NAME:$EUREKA_USER_PASS@host.docker.internal:8761/eureka/v2
      - ES_HOSTS=http://lyrics-elasticsearch:9200
      - ES_INDEX=zipkin
      - JAVA_OPTS=-Xms128m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    ports:
      - "9411:9411"
    depends_on:
      - discovery-server

  discovery-server:
    container_name: discovery-server
    image: hernancussi/java-lyrics-discovery-server:latest
    env_file:
      - .env
    environment:
      - JAVA_OPTS="--enable-preview"
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-server/logs:/workspace/logs

  api-gateway-service:
    container_name: api-gateway-service
    image: hernancussi/java-lyrics-api-gateway-service:latest
    env_file:
      - .env
    environment:
      - JAVA_OPTS="--enable-preview"
      - EUREKA_SERVER=discovery-server
      - REDIS_HOST=lyrics-redis
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway-service/logs:/workspace/logs
    depends_on:
      - discovery-server
      - redis
