global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
#  - "one_rule.yml"

scrape_configs:
  - job_name: 'lyrics-prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
        'host.docker.internal:8080', # api-gateway
        'host.docker.internal:8081', # authentication
        'host.docker.internal:8083', # lyrics
        'host.docker.internal:8084' # logging
      ]
    basic_auth:
      username: admin
      password: pass
